### ISSUE TITLE
Tooltip extension conflicts with Resources Extension on Builder

### ISSUE THREAD

**Issue by robmausser** [NayanKhedkar/adapt-tooltip#1]
On the builder, the tooltip extension replaces the settings for the Resources. 

Did you use the Resources extension to build this? It destroys the Resources section on the builder. I'm guessing you messed something up in the properties.schema.

**Comment by robmausser** [comment]
I fixed it myself. Change line 18 in properties.schema to _tooltip. You have it as _resources.

**Comment by NayanKhedkar** [comment]
Thanks ! @robmausser  for the verify.
